### PR TITLE
Update APIs.guru description and links

### PR DESCRIPTION
**Pull request by MikeRalphson**

### CODE REVIEW

**Comment by xrysanthos** [comment]
Thanks mate!

**Comment by MikeRalphson** [comment]
No problem, I'm the APIs.guru openapi-directory maintainer, so if you've ever got any questions / want to collaborate on a blog post etc, just let me know!

**Comment by xrysanthos** [comment]
I know who you are Mike and I follow your work - thanks for everything!

**Comment by MikeRalphson** [comment]
Oh yes! https://github.com/Mermade/swagger2openapi/issues/16 😺

**Pull request merged**
